### ISSUE TITLE
Disable "Is castrated" when animal sex is female

### ISSUE THREAD

**Issue by immivxt** [paul121/farm-tugboat-demo#21]
"Is Castrated" option in animal asset in case of female is enabled by default.
Kindly disable it

**Comment by paul121** [comment]
Thanks for the feedback @immivxt ! I updated your issue title and am going to transfer this over to the core farmOS issue queue.

It seems that this was requested on our forum as well (farmOS v1 at the time): https://farmos.discourse.group/t/interconnected-field/598

**Comment by paul121** [comment]
Ah - actually I cannot transfer this to farmOS/farmOS because it is another organization. I will open a feature request over there.
