### ISSUE TITLE
can't create a demo

### ISSUE THREAD

**Issue by tamarmot** [paul121/farm-tugboat-demo#24]
When I try to create a demo I get
Error creating demo: Error retrieving demo link from the Tugboat API. Please try again.

**Comment by tamarmot** [comment]
oops, duplicate.

**Comment by paul121** [comment]
Sorry @tamarmot . I've spent some time chasing this in the past but couldn't completely solve it, even tried adding a retry loop for failures. It seems like the Tugboat API just doesn't work some of the time. Were you able to make a demo?
