### ISSUE TITLE
Unable to Sign Up due to TugBoat

### ISSUE THREAD

**Issue by MH-Surge** [paul121/farm-tugboat-demo#25]
Hello,

I tried to create a demo instance and was unable to, please advise.

**Comment by paul121** [comment]
Hi @MH-Surge did you get a particular error message? Sometimes there is too much demand and we cannot make more demos. If you wait a few hours it might be available.

Also, the tugboat demos are not for "signing up" but rather just quick demo testing of farmOS. If you are interested in signing up and using a free trial of farmOS you should try https://farmier.com.

**Comment by MH-Surge** [comment]
Thanks for the heads up. I'll give it another spin
