### ISSUE TITLE
Support Field Kit

### ISSUE THREAD

**Issue by paul121** [paul121/farm-tugboat-demo#9]
This will depend on #8 

Other things:
- `drush en farm_fieldkit`
- ...

**Comment by paul121** [comment]
Oh! `farm_fieldkit` is enabled by default so this step is not required. The only remaining thing is that `https://develop.farmos.app` is not on the CORS allowed origins list for the `fieldkit` client.

I'm not sure if there is an easy way to edit the consumer programmatically during the tugboat build since this is not configuration, but a field on the consumer content entity... we may need to run a php script that searches for the `fieldkit` consumer and updates the field accordingly.

I also looked into modifying the `cors.config` value in `services.yml`. I was able to manually edit the config to have the correct allowed origins but it does require a few steps. That could be automated by providing and copying a `services.yml` file from this repo, using `sed` to edit the file, or maybe even the drupal console `drupal services:override` command (although I tried this and it seems that it does not support assigning array values).

Another question though... should the `farm_fieldkit` module support `https://develop.farmos.app` as an allowed origin?

**Comment by mstenta** [comment]
Hey! Just came to this issue from https://github.com/farmOS/farmOS-client/issues/468...

> `farm_fieldkit` is enabled by default

Just to clarify... `farm_fieldkit` is in the "optional" modules and needs to be explicitly enabled: https://github.com/farmOS/farmOS/blob/d41e4e4e84118a63e129fe3ff4b4ea9bd860fb7f/farm.profile#L59

But it looks like `.tugboat/config.yml` is using `drush site:install ... farm.modules='all'`, so optional modules are being installed as well. :-)

> I'm not sure if there is an easy way to edit the consumer programmatically during the tugboat build since...

Ah seems like you've already looked into what I was suggesting here: https://github.com/farmOS/farmOS-client/issues/468#issuecomment-1002259891

Hmm. Well there must be a way to do it. And it would be nice if it could somehow be configurable perhaps... so that other Netlify branch preview URLs could be used instead of `develop.farmos.app`. I don't quite understand enough about how this repo works to make any suggestions though... the `services.yml` approach might be the most flexible?

**Comment by paul121** [comment]
Oops, thanks for catching that @mstenta !! `farm_fieldkit` is definitely an optional module!

> And it would be nice if it could somehow be configurable perhaps... so that other Netlify branch preview URLs could be used instead of develop.farmos.app.

Yes! So actually, the easiest solution might be to just grant the `manager` user permission to CRUD consumer entities. This won't automate the `develop.farmos.app` origin, but would allow it (and other domains) to be added manually after creating a new demo instance.

More generally, I think I should create a new "Demo administrator" role that has the "admin" permissions that are safe to grant to demo users. I'm hesitant to give users access to the `admin` user itself (although this is fairly low risk being a tugboat instance) but surely some additional permissions could be granted to the demo user.

**Comment by mstenta** [comment]
Good idea @paul121 - creating a demo admin role with the necessary permissions seems like the best approach.

I don't think the manager role should have access to this (although maybe needs more thought). In practice that role tends to get granted pretty liberally, and ideally this kind of oauth config stuff should be strictly "admin".

FWIW, in Farmier I provide a "Farmier Account Admin" role for this purpose. That role gets access to the `farm/settings` forms, among other things that are a bit more admin-y than the manager role IMO. So it's the same basic idea.

For folks who are self-hosting, they obviously already have user 1 access, so this is mainly just a consideration for hosted instances.

**Comment by paul121** [comment]
> I don't think the manager role should have access to this (although maybe needs more thought). In practice that role tends to get granted pretty liberally, and ideally this kind of oauth config stuff should be strictly "admin".

Yes I agree! I only meant to grant that here for the `manager` demo user, not the `manager` role :-)

**Comment by paul121** [comment]
Done! I created a new `demo_admin` role that has the ability to edit consumers, including the CORS origin property needed here. The role provides some other permissions as well.

https://github.com/paul121/farm-tugboat-demo/blob/main/drupal/config/user.role.demo_admin.yml
